from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import JSONField


class AMLCase(models.Model):
    """
    Anti-Money Laundering investigation case
    """
    CASE_TYPES = (
        ('structuring', 'Structuring/Smurfing'),
        ('layering', 'Layering Patterns'),
        ('integration', 'Integration Detection'),
        ('round_numbers', 'Suspicious Round Numbers'),
        ('shell_company', 'Shell Company Detection'),
        ('high_risk_country', 'High-Risk Country Transfers'),
        ('unusual_business', 'Unusual Business Patterns'),
        ('rapid_movement', 'Rapid Money Movement'),
        ('circular_flow', 'Circular Flow Detection'),
        ('party_connection', 'Party Connection Analysis'),
    )
    
    STATUS_CHOICES = (
        ('open', 'Open'),
        ('investigating', 'Under Investigation'),
        ('pending_review', 'Pending Review'),
        ('closed_legitimate', 'Closed - Legitimate'),
        ('closed_suspicious', 'Closed - Suspicious'),
        ('reported', 'Reported to Authorities'),
    )
    
    RISK_LEVELS = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    )
    
    case_id = models.CharField(max_length=100, unique=True)
    case_type = models.CharField(max_length=20, choices=CASE_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='open')
    risk_level = models.CharField(max_length=10, choices=RISK_LEVELS, default='medium')
    
    # Case details
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    detection_method = models.CharField(max_length=100)  # e.g., 'automated', 'manual', 'reported'
    
    # Involved entities
    primary_user_id = models.CharField(max_length=100, null=True, blank=True)
    related_user_ids = JSONField(null=True, blank=True)  # List of related user IDs
    primary_transaction_id = models.CharField(max_length=100, null=True, blank=True)
    related_transaction_ids = JSONField(null=True, blank=True)  # List of related transaction IDs
    
    # Case management
    assigned_to = models.CharField(max_length=100, null=True, blank=True)
    assigned_at = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    
    # Regulatory reporting
    is_reportable = models.BooleanField(default=False)
    report_type = models.CharField(max_length=50, null=True, blank=True)  # e.g., 'SAR', 'CTR'
    report_filed_at = models.DateTimeField(null=True, blank=True)
    report_reference = models.CharField(max_length=100, null=True, blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    closed_at = models.DateTimeField(null=True, blank=True)
    created_by = models.CharField(max_length=100, null=True, blank=True)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    
    class Meta:
        db_table = 'aml_cases'
        indexes = [
            models.Index(fields=['case_id']),
            models.Index(fields=['case_type']),
            models.Index(fields=['status']),
            models.Index(fields=['risk_level']),
            models.Index(fields=['assigned_to']),
            models.Index(fields=['created_at']),
        ]
        
    def __str__(self):
        return f"{self.case_id} - {self.title}"


class AMLCaseNote(models.Model):
    """
    Notes for AML investigation cases
    """
    case = models.ForeignKey(AMLCase, on_delete=models.CASCADE, related_name='notes')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)
    
    class Meta:
        db_table = 'aml_case_notes'
        indexes = [
            models.Index(fields=['case']),
            models.Index(fields=['created_at']),
        ]


class AMLCaseEvidence(models.Model):
    """
    Evidence attached to AML cases
    """
    case = models.ForeignKey(AMLCase, on_delete=models.CASCADE, related_name='evidence')
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    file_path = models.CharField(max_length=255, null=True, blank=True)
    file_type = models.CharField(max_length=50, null=True, blank=True)
    content_type = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100)
    
    class Meta:
        db_table = 'aml_case_evidence'
        indexes = [
            models.Index(fields=['case']),
            models.Index(fields=['created_at']),
        ]


class AMLAlert(models.Model):
    """
    AML alerts generated by detection algorithms
    """
    ALERT_TYPES = (
        ('structuring', 'Structuring/Smurfing'),
        ('layering', 'Layering Patterns'),
        ('integration', 'Integration Detection'),
        ('round_numbers', 'Suspicious Round Numbers'),
        ('shell_company', 'Shell Company Detection'),
        ('high_risk_country', 'High-Risk Country Transfers'),
        ('unusual_business', 'Unusual Business Patterns'),
        ('rapid_movement', 'Rapid Money Movement'),
        ('circular_flow', 'Circular Flow Detection'),
        ('party_connection', 'Party Connection Analysis'),
    )
    
    STATUS_CHOICES = (
        ('new', 'New'),
        ('reviewing', 'Under Review'),
        ('escalated', 'Escalated to Case'),
        ('dismissed', 'Dismissed'),
    )
    
    SEVERITY_LEVELS = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    )
    
    alert_id = models.CharField(max_length=100, unique=True)
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    severity = models.CharField(max_length=10, choices=SEVERITY_LEVELS, default='medium')
    
    # Alert details
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    detection_rule = models.CharField(max_length=100, null=True, blank=True)
    
    # Involved entities
    user_id = models.CharField(max_length=100, null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True, blank=True)
    related_entities = JSONField(null=True, blank=True)  # Additional related entities
    
    # Alert management
    assigned_to = models.CharField(max_length=100, null=True, blank=True)
    assigned_at = models.DateTimeField(null=True, blank=True)
    
    # Case reference (if escalated)
    case = models.ForeignKey(AMLCase, null=True, blank=True, on_delete=models.SET_NULL, related_name='alerts')
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        db_table = 'aml_alerts'
        indexes = [
            models.Index(fields=['alert_id']),
            models.Index(fields=['alert_type']),
            models.Index(fields=['status']),
            models.Index(fields=['severity']),
            models.Index(fields=['user_id']),
            models.Index(fields=['transaction_id']),
            models.Index(fields=['created_at']),
        ]
        
    def __str__(self):
        return f"{self.alert_id} - {self.title}"


class AMLRiskProfile(models.Model):
    """
    Risk profiles for users or entities
    """
    RISK_LEVELS = (
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    )
    
    entity_type = models.CharField(max_length=50)  # e.g., 'user', 'merchant', 'account'
    entity_id = models.CharField(max_length=100)
    risk_level = models.CharField(max_length=10, choices=RISK_LEVELS, default='medium')
    risk_score = models.FloatField(default=0.0)
    risk_factors = JSONField(null=True, blank=True)  # Factors contributing to risk
    
    # Profile details
    last_assessment = models.DateTimeField(default=timezone.now)
    next_assessment = models.DateTimeField(null=True, blank=True)
    
    # History
    previous_risk_level = models.CharField(max_length=10, choices=RISK_LEVELS, null=True, blank=True)
    risk_level_change_date = models.DateTimeField(null=True, blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'aml_risk_profiles'
        indexes = [
            models.Index(fields=['entity_type', 'entity_id']),
            models.Index(fields=['risk_level']),
            models.Index(fields=['last_assessment']),
        ]
        unique_together = ('entity_type', 'entity_id')


class AMLTransactionPattern(models.Model):
    """
    Detected transaction patterns for AML monitoring
    """
    PATTERN_TYPES = (
        ('structuring', 'Structuring/Smurfing'),
        ('layering', 'Layering Patterns'),
        ('round_amounts', 'Round Amount Transactions'),
        ('velocity', 'Unusual Velocity'),
        ('circular', 'Circular Flow'),
        ('fragmented', 'Fragmented Transactions'),
    )
    
    pattern_id = models.CharField(max_length=100, unique=True)
    pattern_type = models.CharField(max_length=20, choices=PATTERN_TYPES)
    
    # Pattern details
    description = models.TextField()
    detection_criteria = JSONField()
    confidence_score = models.FloatField(default=0.0)
    
    # Involved entities
    primary_entity_type = models.CharField(max_length=50)
    primary_entity_id = models.CharField(max_length=100)
    related_entities = JSONField(null=True, blank=True)
    transaction_ids = JSONField()  # List of transaction IDs in the pattern
    
    # Pattern visualization
    graph_data = JSONField(null=True, blank=True)  # Data for network visualization
    
    # Alert reference
    alert = models.ForeignKey(AMLAlert, null=True, blank=True, on_delete=models.SET_NULL, related_name='patterns')
    
    # Timestamps
    detected_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'aml_transaction_patterns'
        indexes = [
            models.Index(fields=['pattern_id']),
            models.Index(fields=['pattern_type']),
            models.Index(fields=['primary_entity_type', 'primary_entity_id']),
            models.Index(fields=['detected_at']),
        ]


class AMLWatchList(models.Model):
    """
    Watch lists for AML monitoring (sanctions, PEPs, etc.)
    """
    LIST_TYPES = (
        ('sanctions', 'Sanctions List'),
        ('pep', 'Politically Exposed Persons'),
        ('high_risk', 'High Risk Entities'),
        ('internal', 'Internal Watch List'),
    )
    
    name = models.CharField(max_length=255)
    list_type = models.CharField(max_length=20, choices=LIST_TYPES)
    description = models.TextField(null=True, blank=True)
    source = models.CharField(max_length=100)  # e.g., 'OFAC', 'EU', 'UN', 'internal'
    is_active = models.BooleanField(default=True)
    
    # List management
    last_updated = models.DateTimeField(default=timezone.now)
    update_frequency = models.CharField(max_length=50, null=True, blank=True)  # e.g., 'daily', 'weekly', 'monthly'
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'aml_watch_lists'
        indexes = [
            models.Index(fields=['list_type']),
            models.Index(fields=['is_active']),
        ]
        
    def __str__(self):
        return f"{self.name} ({self.source})"


class AMLWatchListEntry(models.Model):
    """
    Entries in AML watch lists
    """
    watch_list = models.ForeignKey(AMLWatchList, on_delete=models.CASCADE, related_name='entries')
    
    # Entity information
    name = models.CharField(max_length=255)
    alternate_names = JSONField(null=True, blank=True)  # List of alternate names
    entity_type = models.CharField(max_length=50)  # e.g., 'individual', 'organization', 'country'
    
    # Identification
    identifier_type = models.CharField(max_length=50, null=True, blank=True)  # e.g., 'passport', 'tax_id', 'registration'
    identifier_value = models.CharField(max_length=100, null=True, blank=True)
    nationality = models.CharField(max_length=2, null=True, blank=True)
    
    # Risk information
    risk_category = models.CharField(max_length=50, null=True, blank=True)
    listing_reason = models.TextField(null=True, blank=True)
    
    # Source information
    source_id = models.CharField(max_length=100, null=True, blank=True)  # ID in the original source
    source_url = models.URLField(null=True, blank=True)
    
    # Status
    is_active = models.BooleanField(default=True)
    
    # Timestamps
    listed_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'aml_watch_list_entries'
        indexes = [
            models.Index(fields=['watch_list']),
            models.Index(fields=['name']),
            models.Index(fields=['entity_type']),
            models.Index(fields=['is_active']),
        ]
        
    def __str__(self):
        return f"{self.name} ({self.entity_type})"
