import React, { useState } from 'react';
import { Search, Filter, Bell, AlertTriangle, Clock, User, ChevronRight, X } from 'lucide-react';
import Badge from '../components/common/Badge';
import { alerts } from '../services/mockData';
import { formatTimestamp } from '../utils/formatters';

const severityConfig = {
  critical: { color: 'var(--danger-600)', bg: 'var(--danger-50)', icon: '🔴' },
  high: { color: 'var(--warning-600)', bg: 'var(--warning-50)', icon: '🟠' },
  medium: { color: '#ca8a04', bg: '#fefce8', icon: '🟡' },
  low: { color: 'var(--success-600)', bg: 'var(--success-50)', icon: '🟢' },
};

const AlertDetail = ({ alert, onClose }) => (
  <div style={{
    position: 'fixed', top: 0, right: 0, width: '520px', height: '100vh',
    background: 'white', boxShadow: 'var(--shadow-xl)', zIndex: 1000,
    display: 'flex', flexDirection: 'column', animation: 'slideInRight 0.2s ease-out',
  }}>
    <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--slate-200)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <h3 style={{ fontSize: '16px', fontWeight: 700 }}>{alert.id}</h3>
          <Badge status={alert.severity} />
        </div>
        <span style={{ fontSize: '12px', color: 'var(--slate-500)' }}>{formatTimestamp(alert.timestamp)}</span>
      </div>
      <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--slate-400)', padding: '4px' }}><X size={20} /></button>
    </div>
    <div style={{ flex: 1, overflow: 'auto', padding: '24px' }}>
      <h4 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '8px' }}>{alert.title}</h4>
      <p style={{ fontSize: '14px', color: 'var(--slate-600)', lineHeight: 1.6, marginBottom: '24px' }}>{alert.description}</p>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '24px' }}>
        {[
          { label: 'Type', value: alert.type },
          { label: 'Status', value: alert.status },
          { label: 'Risk Score', value: alert.riskScore },
          { label: 'Assignee', value: alert.assignee || 'Unassigned' },
        ].map(item => (
          <div key={item.label} style={{ padding: '12px', background: 'var(--slate-50)', borderRadius: 'var(--radius-md)' }}>
            <div style={{ fontSize: '11px', color: 'var(--slate-500)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{item.label}</div>
            <div style={{ fontSize: '14px', fontWeight: 500, marginTop: '4px' }}>{item.value}</div>
          </div>
        ))}
      </div>

      <div style={{ borderTop: '1px solid var(--slate-200)', paddingTop: '20px' }}>
        <h4 style={{ fontSize: '14px', fontWeight: 600, marginBottom: '12px' }}>Timeline</h4>
        {[
          { time: '14:20:00', action: 'Alert generated by detection engine', user: 'System' },
          { time: '14:22:15', action: 'Auto-assigned to analyst', user: 'System' },
          { time: '14:25:30', action: 'Investigation started', user: alert.assignee || 'Analyst' },
        ].map((entry, i) => (
          <div key={i} style={{ display: 'flex', gap: '12px', marginBottom: '16px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
              <div style={{ width: 10, height: 10, borderRadius: '50%', background: i === 0 ? 'var(--primary-500)' : 'var(--slate-300)', flexShrink: 0 }} />
              {i < 2 && <div style={{ width: 2, height: 32, background: 'var(--slate-200)' }} />}
            </div>
            <div>
              <div style={{ fontSize: '13px', fontWeight: 500 }}>{entry.action}</div>
              <div style={{ fontSize: '11px', color: 'var(--slate-400)', marginTop: '2px' }}>{entry.time} • {entry.user}</div>
            </div>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: '8px', marginTop: '20px' }}>
        <button style={{
          flex: 1, padding: '10px', borderRadius: 'var(--radius-md)',
          background: 'var(--primary-600)', color: 'white', border: 'none',
          fontSize: '13px', fontWeight: 600, cursor: 'pointer',
        }}>Escalate to Case</button>
        <button style={{
          flex: 1, padding: '10px', borderRadius: 'var(--radius-md)',
          background: 'var(--success-600)', color: 'white', border: 'none',
          fontSize: '13px', fontWeight: 600, cursor: 'pointer',
        }}>Dismiss Alert</button>
      </div>
    </div>
  </div>
);

const Alerts = () => {
  const [search, setSearch] = useState('');
  const [severityFilter, setSeverityFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [selectedAlert, setSelectedAlert] = useState(null);

  const filtered = alerts.filter(a => {
    if (severityFilter !== 'all' && a.severity !== severityFilter) return false;
    if (statusFilter !== 'all' && a.status !== statusFilter) return false;
    if (search && !a.title.toLowerCase().includes(search.toLowerCase()) && !a.id.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const counts = {
    critical: alerts.filter(a => a.severity === 'critical').length,
    high: alerts.filter(a => a.severity === 'high').length,
    medium: alerts.filter(a => a.severity === 'medium').length,
    low: alerts.filter(a => a.severity === 'low').length,
  };

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px' }}>
        {Object.entries(counts).map(([severity, count]) => (
          <div key={severity}
            onClick={() => setSeverityFilter(severityFilter === severity ? 'all' : severity)}
            style={{
              background: severityFilter === severity ? severityConfig[severity].bg : 'white',
              borderRadius: 'var(--radius-lg)', padding: '16px 20px',
              border: `1px solid ${severityFilter === severity ? severityConfig[severity].color + '40' : 'var(--slate-200)'}`,
              cursor: 'pointer', transition: 'var(--transition-fast)',
            }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
              <span>{severityConfig[severity].icon}</span>
              <span style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase', color: severityConfig[severity].color, letterSpacing: '0.05em' }}>{severity}</span>
            </div>
            <div style={{ fontSize: '28px', fontWeight: 700, color: 'var(--slate-900)' }}>{count}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: '8px', flex: 1, minWidth: '300px',
          background: 'white', borderRadius: 'var(--radius-md)', padding: '8px 16px',
          border: '1px solid var(--slate-200)',
        }}>
          <Search size={16} color="var(--slate-400)" />
          <input type="text" placeholder="Search alerts..." value={search} onChange={e => setSearch(e.target.value)}
            style={{ flex: 1, border: 'none', outline: 'none', fontSize: '13px', background: 'transparent' }} />
        </div>
        {['all', 'open', 'investigating', 'escalated', 'closed'].map(s => (
          <button key={s} onClick={() => setStatusFilter(s)} style={{
            padding: '8px 14px', borderRadius: 'var(--radius-md)', border: '1px solid',
            borderColor: statusFilter === s ? 'var(--primary-500)' : 'var(--slate-200)',
            background: statusFilter === s ? 'var(--primary-50)' : 'white',
            color: statusFilter === s ? 'var(--primary-700)' : 'var(--slate-600)',
            fontSize: '12px', fontWeight: 500, cursor: 'pointer', textTransform: 'capitalize',
          }}>{s === 'all' ? 'All Status' : s}</button>
        ))}
      </div>

      {/* Alert List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {filtered.map(alert => (
          <div key={alert.id}
            onClick={() => setSelectedAlert(alert)}
            style={{
              background: 'white', borderRadius: 'var(--radius-lg)', padding: '16px 20px',
              border: '1px solid var(--slate-200)', cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: '16px',
              transition: 'var(--transition-fast)', boxShadow: 'var(--shadow-sm)',
            }}
            onMouseEnter={e => { e.currentTarget.style.boxShadow = 'var(--shadow-md)'; e.currentTarget.style.borderColor = 'var(--slate-300)'; }}
            onMouseLeave={e => { e.currentTarget.style.boxShadow = 'var(--shadow-sm)'; e.currentTarget.style.borderColor = 'var(--slate-200)'; }}
          >
            <div style={{
              width: 40, height: 40, borderRadius: 'var(--radius-md)',
              background: severityConfig[alert.severity].bg,
              display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
            }}>
              <AlertTriangle size={18} color={severityConfig[alert.severity].color} />
            </div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                <span style={{ fontSize: '12px', fontFamily: 'monospace', color: 'var(--slate-500)' }}>{alert.id}</span>
                <Badge status={alert.severity} />
                <Badge status={alert.status} />
              </div>
              <div style={{ fontSize: '14px', fontWeight: 600, color: 'var(--slate-800)', marginBottom: '2px' }} className="truncate">{alert.title}</div>
              <div style={{ fontSize: '12px', color: 'var(--slate-500)' }} className="truncate">{alert.description}</div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px', flexShrink: 0 }}>
              <span style={{ fontSize: '11px', color: 'var(--slate-400)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <Clock size={12} /> {formatTimestamp(alert.timestamp)}
              </span>
              {alert.assignee && (
                <span style={{ fontSize: '11px', color: 'var(--slate-500)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <User size={12} /> {alert.assignee}
                </span>
              )}
              <div style={{
                fontSize: '18px', fontWeight: 800, fontFamily: 'monospace',
                color: alert.riskScore >= 80 ? 'var(--danger-600)' : alert.riskScore >= 60 ? 'var(--warning-600)' : 'var(--info-600)',
              }}>{alert.riskScore}</div>
            </div>
            <ChevronRight size={16} color="var(--slate-300)" />
          </div>
        ))}
      </div>

      {selectedAlert && (
        <>
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.3)', zIndex: 999 }} onClick={() => setSelectedAlert(null)} />
          <AlertDetail alert={selectedAlert} onClose={() => setSelectedAlert(null)} />
        </>
      )}
    </div>
  );
};

export default Alerts;
